# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlantTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlantTracker
  pod 'AssetsPickerViewController', '~> 2.6'
  pod 'TwicketSegmentedControl'
  pod "KeyboardObserver", '~> 2.1'
  pod 'ImageTransition'
end

